### ISSUE TITLE
按照你的教程做现在直接下载的最新版webpack和webpack-cli会出问题

### ISSUE THREAD

**Issue by clouddemo1** [ZakingQ/bundler-demo#1]
现在按照你的教程做现在直接下载的最新版webpack和webpack-cli会出问题

搜了半天，终于明白了写死成旧版才终于编译通过，网上文档也不太清楚好不容易才明白^4.2.0这个的意思，对我这种新手实在太难了啊。。。
    "webpack": "4.2.0",
    "webpack-cli": "2.0.12",

能否每一步都保存一个镜像好对比

**Comment by ZakingQ** [comment]
后面会考虑的，本身这个项目几乎全是webpack3.6的功能，webpack4的内容比较少，所以后期会打算每一个步骤弄一个分支，并且重新写一下博客上的内容
